# Generated by Django 5.2.8 on 2025-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10)),
                ('car_name', models.CharField(max_length=10)),
                ('enginum', models.IntegerField()),
                ('release', models.DateField()),
            ],
        ),
    ]
